--------------------------------------------------------
--  File created - Tuesday-February-02-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "SYS"."COMMENTS" 
   (	"REVIEW_ID" VARCHAR2(10 BYTE), 
	"AUTHOR_ID" VARCHAR2(10 BYTE), 
	"TEXTUAL_CONTENT" VARCHAR2(100 BYTE), 
	"COMMENT_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVIEWS
--------------------------------------------------------

  CREATE TABLE "SYS"."REVIEWS" 
   (	"ID" VARCHAR2(10 BYTE), 
	"PUBLISH_DATE" TIMESTAMP (0) WITH TIME ZONE, 
	"STARS" VARCHAR2(10 BYTE), 
	"AUTHOR" VARCHAR2(10 BYTE), 
	"BELONGS_TO_BUSINESS" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SYS"."USERS" 
   (	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(45 BYTE), 
	"YELP_ID" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"BIRTH_PLACE" VARCHAR2(50 BYTE), 
	"BIRTH_DATE" DATE, 
	"GENDER" VARCHAR2(5 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.COMMENTS
SET DEFINE OFF;
Insert into SYS.COMMENTS (REVIEW_ID,AUTHOR_ID,TEXTUAL_CONTENT,COMMENT_DATE) values ('R2','Y3',null,null);
Insert into SYS.COMMENTS (REVIEW_ID,AUTHOR_ID,TEXTUAL_CONTENT,COMMENT_DATE) values ('R2','Y2',null,null);
Insert into SYS.COMMENTS (REVIEW_ID,AUTHOR_ID,TEXTUAL_CONTENT,COMMENT_DATE) values ('R3','Y3',null,null);
Insert into SYS.COMMENTS (REVIEW_ID,AUTHOR_ID,TEXTUAL_CONTENT,COMMENT_DATE) values ('R7','Y8',null,null);
Insert into SYS.COMMENTS (REVIEW_ID,AUTHOR_ID,TEXTUAL_CONTENT,COMMENT_DATE) values ('R7','Y11',null,null);
Insert into SYS.COMMENTS (REVIEW_ID,AUTHOR_ID,TEXTUAL_CONTENT,COMMENT_DATE) values ('R15','Y8',null,null);
Insert into SYS.COMMENTS (REVIEW_ID,AUTHOR_ID,TEXTUAL_CONTENT,COMMENT_DATE) values ('R16','Y8',null,null);
Insert into SYS.COMMENTS (REVIEW_ID,AUTHOR_ID,TEXTUAL_CONTENT,COMMENT_DATE) values ('R20','Y7',null,null);
Insert into SYS.COMMENTS (REVIEW_ID,AUTHOR_ID,TEXTUAL_CONTENT,COMMENT_DATE) values ('R20','Y10',null,null);
--------------------------------------------------------
--  DDL for Index SYS_C007699
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."SYS_C007699" ON "SYS"."COMMENTS" ("REVIEW_ID", "AUTHOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "SYS"."COMMENTS" ADD PRIMARY KEY ("REVIEW_ID", "AUTHOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYS"."COMMENTS" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."COMMENTS" MODIFY ("REVIEW_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "SYS"."COMMENTS" ADD CONSTRAINT "COMMENT_OWNER" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "SYS"."USERS" ("YELP_ID") ENABLE;
  ALTER TABLE "SYS"."COMMENTS" ADD CONSTRAINT "REVIEW_COMMENT" FOREIGN KEY ("REVIEW_ID")
	  REFERENCES "SYS"."REVIEWS" ("ID") ON DELETE CASCADE ENABLE;
